// 账户中心-账户类型
const ACCOUNT_TYPE = 'ACCOUNT_TITLE';
// 资产类型
const ASSET_TYPE = 'ASSET_KIND';
// 审核状态
const AUDIT_STATUS = 'AUDIT_STATUS';
const AUDIT_STATUS_WAIT_AUDIT = 'AUDITING'; // 待审核
const AUDIT_STATUS_PASS = 'AUDIT_PASS'; // 审核通过
const AUDIT_STATUS_NOT_PASS = 'AUDIT_NOT_PASS'; // 审核不通过
const AUDIT_STATUS_EVALUATING = 'EVALUATING'; // 评估中
const AUDIT_STATUS_WAIT_EVALUATE = 'WAIT_EVALUATE'; // 待评估
// 审核进度
const AUDIT_STEP = 'AUDITING';
const AUDIT_STEP_GROUP = 'AUDIT';
// 数据报告验证内容
const AUDIT_TYPE = 'ASSET_AUDIT';
const AUDIT_TYPE_POSITIVE_ASSET = 'POSITIVE_ASSET';
const AUDIT_TYPE_CLIENT_INFO = 'CLIENT_INFO_AUDIT'; // 客户身份信息验证
const AUDIT_TYPE_MANUAL_CHECK = 'MANUAL_CHECK';
const AUDIT_TYPE_AUTO_CHECK = 'AUTO_CHECK';
// 银行名称
const BANK = 'BANK';
// 银行卡认证状态
const BANK_CARD_AUTH_STATUS = 'AUTH_STATUS';
const BANK_CARD_AUTH_STATUS_SUCCESS = 'AUTH_SUCCESS';
const BANK_CARD_AUTH_STATUS_AUTHERIZED = 'AUTHERIZED';
const BANK_CARD_AUTH_STATUS_UNAUTHERIZED = 'UNAUTHERIZED';
// 银行卡类型 （个人/对公）
const BANK_TYPE = 'BANK_TYPE';
const BANK_TYPE_PERSONAL_CARD = 'PERSONAL_CARD';
const BANK_TYPE_PUBLIC_CARD = 'PUBLIC_CARD';
// 银行卡用途
const BANK_USE_TYPE = 'BANK_USE_TYPE';
const BANK_USE_TYPE_COLLECTION = 'COLLECTION_BANK';
const BANK_USE_TYPE_COMPENSATION = 'COMPENSATION_BANK';
// 账单状态
const BILL_STATUS = 'BILL_STATUS';
// 业务端
const BUSINESS = 'BUSINESS';
const BUSINESS_CENTER = 'CENTER';
const BUSINESS_ASSET = 'ASSET';
const BUSINESS_FUND = 'FUND';
const BUSINESS_INTENTION_FUND = 'INTENTION_FUND';
const BUSINESS_REL_ASSET = 'REL_ASSET';
const BUSINESS_ALL = 'all';
// 车辆使用性质
const CAR_NATURE = 'CAR_NATURE';
// 企业收益
const COMPANY_INCOME = 'ENTERPRISE_INCOME';
// 公司类型
const COMPANY_TYPE = 'COMPANY_TYPE';
// 人员规模
const COMPANY_SCALE = 'PERSONNEL_SCALE';
// 经营状态
const COMPANY_STATUS = 'ORG_STATUS';
// 公司性质
const COMPANY_PROP = 'UNIT';
const COMPANY_PROP_GROUP = 'PROPERTY';
// 协议类型
const CONTRACT_TYPE = 'PROOF_MATERIAL';
const CONTRACT_TYPE_ASSET = 'ASSET_FOR_CHANNEL_COMPENSATORY_PROTOCOL';
const CONTRACT_TYPE_FUND = 'FUND_FOR_CHANNEL_COMPENSATORY_PROTOCOL';
// 企业客户申请人类型
const CUSTOMER_ORG_APPLICANT_TYPE = 'APPLICANT_ORG_RELATION';
// 客户资产类型
const CUSTOMER_PROP_CARD = 'BANK_CARD';
const CUSTOMER_PROP_HOUSE = 'HOUSE';
const CUSTOMER_PROP_CAR = 'CAR';
const CUSTOMER_PROP_DEVICE = 'DEVICE';
const CUSTOMER_PROP_SHOP = 'SHOP';
const CUSTOMER_PROP_ESHOP = 'ELECTRONIC_COMMERCE';
const CUSTOMER_PROP_FUND = 'PUBLIC_RESERVE_FUNDS';
// 学历
const EDUCATION = 'EDUCATION';
const EDUCATION_GROUP = 'EDU';
// 电商平台
const ESHOP_PLATFORM = 'ELECTRONIC_PLATFORM';
// 计费类型
const FEE_CHARGE_TYPE = 'FEE_CHARGING';
const FEE_CHARGE_TYPE_PERCENT = 'RATE_CHARGING';
const FEE_CHARGE_TYPE_AMOUNT = 'FIXED_CHARGING';
// 收费阶段
const FEE_PHASE = 'FEE_PHASE';
const FEE_PHASE_INITIAL = 'INITIAL_FEE';
const FEE_PHASE_MIDTERM = 'MIDTERM_FEE';
const FEE_PHASE_TERMINAL = 'TERMINAL_FEE';
// 会计期间
const FISCAL_PERIOD = 'FISCAL_PERIOD';
// 性别
const GENDER = 'SEX';
// 住房状况
const HOUSE_STATUS = 'HOUSE_PROPERTY';
// 证件类型
const IDENT_TYPE = 'PAPER_TYPE';
const IDENT_TYPE_IDENTITY = 'IDENTITY';
// 年收入
const INCOME_YEAR = 'ANNUAL_SALARY';
// 所属行业
const INDUSTRY = 'INDUSTRY';
// 是否续借
const IS_RENEW_LOAN = 'RENEW_LOANS';
// 放款模式
const LOAN_MODEL = 'LOAN_MODEL';
const LOAN_MODEL_DS = 'COLLECTION';
// 借款属性
const LOAN_PROP = 'LOAN_PROP';
const LOAN_PROP_NEW = 'NEW';
const LOAN_PROP_CONTINUE = 'CONTINUE';
// 新借子分类
const LOAN_PROP_SUB = 'NEW_LOAN_KIND';
const LOAN_PROP_SUB_NEW = 'NEW_ADD';
// 借贷利率
const LOAN_RATES = 'LOAN_RATES';
const LOAN_RATES_YEAR = 'YEAR_RATES';
// 借贷状态
const LOAN_STATUS = 'LOAN_STATUS';
const LOAN_STATUS_GROUP = 'AUDIT';
const LOAN_STATUS_SUBMITTING = 'SUBMITTING';
const LOAN_STATUS_AUDITING = 'AUDITING';
const LOAN_STATUS_REJECTED = 'REJECTED';
const LOAN_STATUS_PENDING_STORAGE = 'PENDING_STORAGE';
const LOAN_STATUS_RAISE_FAIL = 'RAISE_FAIL';
const LOAN_STATUS_WAIT_LEND = 'WAIT_LEND';
const LOAN_STATUS_WAIT_FEEDBACK = 'WAIT_FEEDBACK';
const LOAN_STATUS_FEEDBACK = 'FEEDBACK';
const LOAN_STATUS_WITHDRAWAL = 'WITHDRAWAL';
const LOAN_STATUS_IN_LOAN = 'IN_LOAN';
const LOAN_STATUS_APPLY_ADVANCE = 'APPLY_ADVANCE';
const LOAN_STATUS_APPLY_ADVANCE_FAIL = 'APPLY_ADVANCE_FAIL';
const LOAN_STATUS_CLEARED = 'CLEARED';
const LOAN_STATUS_LOAN_FAIL = 'LOAN_FAIL';
const LOAN_STATUS_NO_SET_REPAYMENT = 'NO_SET_REPAYMENT';
const LOAN_STATUS_LOANED = 'LOANED';
const LOAN_STATUS_WASTE_LOAN = 'WASTE_LOAN';
const LOAN_STATUS_LIST = [ // 顺序同sequence字段，不可随意更改
  'SUBMITTING',             // 0 // 待提交
  'AUDITING',               // 1 // 审核中
  'REJECTED', // deprecated: // 2 // 审核拒绝
  'PENDING_STORAGE',        // 3 // 待收纳
  'RAISE_FAIL', // deprecated: // 4 // 募集失败
  'WAIT_LEND',              // 5 // 待放款
  'WAIT_FEEDBACK',          // 6 // 待反馈
  'FEEDBACK',               // 7 // 已反馈
  'WITHDRAWAL',             // 8 // 撤贷
  'IN_LOAN',                // 9 // 放款中
  'APPLY_ADVANCE',          // 10// 提前结清处理中
  'APPLY_ADVANCE_FAIL', // deprecated: // 11 // 提前结清失败，废弃状态，失败后重置到已放款
  'CLEARED',                // 12// 已结清
  'LOAN_FAIL',              // 13// 放款失败
  'NO_SET_REPAYMENT',       // 14// 已收纳
  'LOANED',                 // 15// 已放款
  'WASTE_LOAN'              // 16// 废贷
];
const LOAN_STATUS_COLOR_MAP = {
  'SUBMITTING': 'danger',
  'AUDITING': 'warning',
  'REJECTED': 'info',
  'PENDING_STORAGE': 'pink',
  'RAISE_FAIL': 'info',
  'WAIT_LEND': '', // 待放款
  'WAIT_FEEDBACK': 'danger', // 待反馈
  'FEEDBACK': 'danger', // 已反馈
  'WITHDRAWAL': 'warning', // 撤贷
  'IN_LOAN': 'warning', // 放款中
  'APPLY_ADVANCE': 'warning',
  'APPLY_ADVANCE_FAIL': 'success', // deprecated: 提前结清失败，废弃状态，失败后重置到已放款
  'CLEARED': 'info', // 已结清
  'LOAN_FAIL': 'info', // 放款失败
  'NO_SET_REPAYMENT': 'pink',
  'LOANED': 'success', // 已放款
  'WASTE_LOAN': 'info'
};
// 贷款类型
const LOAN_TYPE = 'LOAN_KIND';
const LOAN_TYPE_CREDIT = 'CREDIT';
const LOAN_TYPE_MORTGAGE = 'MORTGAGE';
const LOAN_TYPE_PLEDGE = 'PLEDGE';
const LOAN_TYPE_VOUCHER = 'VOUCHER';
// 借款用途
const LOAN_USAGE = 'USAGE_LOAN';
const LOAN_USAGE_GROUP = 'LOAN';
// 婚姻状况
const MARRIAGE_STATUS = 'MARITAL';
// 异常处理状态
const MISTAKE_HANDLE_STATUS_UNHANDLED = 'UNHANDLED';
// 异常类型
const MISTAKE_TYPE_OTHER = 'PAYMENT_OTHER_ERROR';
const MISTAKE_TYPE_WITHDRAW_FAILURE = 'PAYMENT_WITHDRAW_FAILURE';
// 还款来源
const PAYMENT_SOURCE = 'PAYMENT';
// 放款状态
const PAYMENT_STATUS = 'PAYMENT_STATUS';
// 公积金性质
const PF_PROP = 'ACCUMULATION_FUND';
// 业务类型
const PROJECT_TYPE = 'PROJECT_TYPE';
// 项目配置审核状态
const PROJECT_CONFIG_AUDIT_STATUS = 'PROJECT_CONFIG_AUDIT_STATUS';
const PROJECT_CONFIG_AUDIT_STATUS_WAIT_AUDIT = 'AUDITING'; // 待审核
const PROJECT_CONFIG_AUDIT_STATUS_PASS = 'AUDIT_PASS'; // 审核通过
const PROJECT_CONFIG_AUDIT_STATUS_NOT_PASS = 'AUDIT_NOT_PASS'; // 审核不通过
// 证明材料
const PROOF_MATERIAL = 'PROOF_MATERIAL';
const PROOF_MATERIAL_P = 'PERSON';
const PROOF_MATERIAL_O = 'ORG';
const PROOF_MATERIAL_P_ID_CARD = 'USER_IDENTITY';
const PROOF_MATERIAL_P_ID_CARD_BACK = 'USER_IDENTITY_BACK';
const PROOF_MATERIAL_P_ID_CARD_COPY = 'USER_IDENTITY_COPY';
const PROOF_MATERIAL_P_LOAN_APP = 'LOAN_APPLICATION_PROOF_MATERIAL';
const PROOF_MATERIAL_P_LOAN_APP_MOSAIC = 'MOSAIC';
const PROOF_MATERIAL_P_LOAN_APP_PDF = 'LOAN_APPLICATION_PROOF_MATERIAL_PDF';
const PROOF_MATERIAL_O_LOGO = 'COM_LOGO';
const PROOF_MATERIAL_O_LEGAL_IDENT = 'LEGAL_PERSON_IDENT';
const PROOF_MATERIAL_O_CONTRACT = 'ORG_RELATION_PACT_MATERIAL';
const PROOF_MATERIAL_O_LICENSE = 'COM_BUSINESS_LICENSE';
const PROOF_MATERIAL_O_PERMIT = 'COM_ACCOUNT_PERMITS';
const PROOF_MATERIAL_O_TAX = 'COM_TAX_REGISTRATION_CERTIFICATE';
const PROOF_MATERIAL_O_OTHER = 'COM_OTHER_MATERIAL';
// 保障模式
const PROTECTION_MODEL = 'PROTECTION_PLAN';
const PROTECTION_MODEL_COMPENSATORY = 'PLACE_COMPENSATORY';
// 公积金账户状态
const PUBLIC_ACC_STATUS = 'PUBLIC_ACC_STATUS';
// 朋友关系
const REL_FRIEND = 'FRIENDSHIP';
const REL_FRIEND_LIST = [
  'PP_COLLEAGUE',
  'PP_CLASSMATE',
  'PP_FRIEND'
];
// 亲属关系
const REL_RELATIVE = 'RELATIONSHIP';
const REL_RELATIVE_LIST = [
  'PP_FATHER',
  'PP_MOTHER',
  'PP_BROTHER',
  'PP_SISTERS',
  'PP_SPOUSE',
  'PP_CHILDREN'
];
// 当事者关系
const REL_OP_FIRST_CONTACTOR = 'OP_FIRST_CONTACTOR';
const REL_OP_LEGAL_PERSON = 'OP_LEGAL_PERSON';
// 还款模式
const REPAY_MODEL = 'REPAY_MODEL';
// 还款状态
const REPAY_STATUS = 'REPAY_PLAN_STATUS';
// 还款期限范围
const REPAY_TIME_RANGE = 'REPAY_TIME_RANGE';
// 还款方式
const REPAY_WAY = 'REPAY_WAY';
// 风控类型
const RISK_TYPE = 'RISK_TYPE';
const RISK_TYPE_GROUP = 'RISK';
// 风险等级
const RISK_LEVEL = 'ASSET_LEVEL';
const RISK_LEVEL_GROUP = 'EVALUATION';
// 风险承担方式
const RISK_TAKING_TYPE = 'RISK_TAKING_TYPE';
// 时间类型
const SEARCH_DATE_TYPE = 'SEARCH_DATE';
const SEARCH_DATE_TYPE_APPLY = 'APPLY_DATE';
const SEARCH_DATE_TYPE_LOAN = 'LOAN_DATE';
// 服务方式
const SERVICE_TYPE = 'ORG_SERVICE_TYPE';
const SERVICE_TYPE_ASSET = 'ASSET';
const SERVICE_TYPE_FUND = 'FUND';
// 股东类型
const SHAREHOLDER_TYPE = 'SHAREHOLDER_TYPE';
// 结算模式/会计期间
const STATE_TYPE = 'STATE_TYPE';
// 主体性质
const SUBJECT_PROP = 'SUBJECT_NATURE';
const SUBJECT_PROP_PERSON = 'PERSON_CUSTOMER';
const SUBJECT_PROP_ORGANIZE = 'ORG_CUSTOMER';
// 定时任务状态
const TASK_STATUS = 'TASK_STATUS';
const TASK_STATUS_FAILURE = 'FAILURE';
// 定时任务类型
const TASK_TYPE = 'TASK_TYPE';
// 时间单位
const TERM_UNIT = 'TERM_UNIT';
const TERM_UNIT_DAY = 'DAY';
const TERM_UNIT_NATURAL_MONTH = 'NATURAL_MONTH';
// 工作性质
const WORK_NATURE = 'WORK_NATURE';

export default {
  ACCOUNT_TYPE,
  ASSET_TYPE,
  AUDIT_STATUS,
  AUDIT_STATUS_WAIT_AUDIT,
  AUDIT_STATUS_PASS,
  AUDIT_STATUS_NOT_PASS,
  AUDIT_STATUS_EVALUATING,
  AUDIT_STATUS_WAIT_EVALUATE,
  AUDIT_STEP,
  AUDIT_STEP_GROUP,
  AUDIT_TYPE,
  AUDIT_TYPE_CLIENT_INFO,
  AUDIT_TYPE_POSITIVE_ASSET,
  AUDIT_TYPE_MANUAL_CHECK,
  AUDIT_TYPE_AUTO_CHECK,
  BANK,
  BANK_CARD_AUTH_STATUS,
  BANK_CARD_AUTH_STATUS_SUCCESS,
  BANK_CARD_AUTH_STATUS_AUTHERIZED,
  BANK_CARD_AUTH_STATUS_UNAUTHERIZED,
  BANK_TYPE,
  BANK_TYPE_PERSONAL_CARD,
  BANK_TYPE_PUBLIC_CARD,
  BANK_USE_TYPE,
  BANK_USE_TYPE_COLLECTION,
  BANK_USE_TYPE_COMPENSATION,
  BILL_STATUS,
  BUSINESS,
  BUSINESS_CENTER,
  BUSINESS_ASSET,
  BUSINESS_FUND,
  BUSINESS_INTENTION_FUND,
  BUSINESS_REL_ASSET,
  BUSINESS_ALL,
  CAR_NATURE,
  COMPANY_INCOME,
  COMPANY_TYPE,
  COMPANY_SCALE,
  COMPANY_STATUS,
  COMPANY_PROP,
  COMPANY_PROP_GROUP,
  CONTRACT_TYPE,
  CONTRACT_TYPE_ASSET,
  CONTRACT_TYPE_FUND,
  CUSTOMER_ORG_APPLICANT_TYPE,
  CUSTOMER_PROP_CARD,
  CUSTOMER_PROP_HOUSE,
  CUSTOMER_PROP_CAR,
  CUSTOMER_PROP_DEVICE,
  CUSTOMER_PROP_SHOP,
  CUSTOMER_PROP_ESHOP,
  CUSTOMER_PROP_FUND,
  EDUCATION,
  EDUCATION_GROUP,
  ESHOP_PLATFORM,
  FEE_CHARGE_TYPE,
  FEE_CHARGE_TYPE_PERCENT,
  FEE_CHARGE_TYPE_AMOUNT,
  FEE_PHASE,
  FEE_PHASE_INITIAL,
  FEE_PHASE_MIDTERM,
  FEE_PHASE_TERMINAL,
  FISCAL_PERIOD,
  GENDER,
  HOUSE_STATUS,
  IDENT_TYPE,
  IDENT_TYPE_IDENTITY,
  INCOME_YEAR,
  INDUSTRY,
  IS_RENEW_LOAN,
  LOAN_MODEL,
  LOAN_MODEL_DS,
  LOAN_PROP,
  LOAN_PROP_NEW,
  LOAN_PROP_CONTINUE,
  LOAN_PROP_SUB,
  LOAN_PROP_SUB_NEW,
  LOAN_RATES,
  LOAN_RATES_YEAR,
  LOAN_STATUS,
  LOAN_STATUS_GROUP,
  LOAN_STATUS_SUBMITTING,
  LOAN_STATUS_AUDITING,
  LOAN_STATUS_REJECTED,
  LOAN_STATUS_PENDING_STORAGE,
  LOAN_STATUS_RAISE_FAIL,
  LOAN_STATUS_WAIT_LEND,
  LOAN_STATUS_WAIT_FEEDBACK,
  LOAN_STATUS_FEEDBACK,
  LOAN_STATUS_WITHDRAWAL,
  LOAN_STATUS_IN_LOAN,
  LOAN_STATUS_APPLY_ADVANCE,
  LOAN_STATUS_APPLY_ADVANCE_FAIL,
  LOAN_STATUS_CLEARED,
  LOAN_STATUS_LOAN_FAIL,
  LOAN_STATUS_NO_SET_REPAYMENT,
  LOAN_STATUS_LOANED,
  LOAN_STATUS_WASTE_LOAN,
  LOAN_STATUS_LIST,
  LOAN_STATUS_COLOR_MAP,
  LOAN_TYPE,
  LOAN_TYPE_CREDIT,
  LOAN_TYPE_MORTGAGE,
  LOAN_TYPE_PLEDGE,
  LOAN_TYPE_VOUCHER,
  LOAN_USAGE,
  LOAN_USAGE_GROUP,
  MARRIAGE_STATUS,
  MISTAKE_HANDLE_STATUS_UNHANDLED,
  MISTAKE_TYPE_OTHER,
  MISTAKE_TYPE_WITHDRAW_FAILURE,
  PAYMENT_SOURCE,
  PAYMENT_STATUS,
  PF_PROP,
  PROJECT_TYPE,
  PROJECT_CONFIG_AUDIT_STATUS,
  PROJECT_CONFIG_AUDIT_STATUS_WAIT_AUDIT,
  PROJECT_CONFIG_AUDIT_STATUS_PASS,
  PROJECT_CONFIG_AUDIT_STATUS_NOT_PASS,
  PROOF_MATERIAL,
  PROOF_MATERIAL_P,
  PROOF_MATERIAL_O,
  PROOF_MATERIAL_P_ID_CARD,
  PROOF_MATERIAL_P_ID_CARD_BACK,
  PROOF_MATERIAL_P_ID_CARD_COPY,
  PROOF_MATERIAL_P_LOAN_APP,
  PROOF_MATERIAL_P_LOAN_APP_MOSAIC,
  PROOF_MATERIAL_P_LOAN_APP_PDF,
  PROOF_MATERIAL_O_LOGO,
  PROOF_MATERIAL_O_LEGAL_IDENT,
  PROOF_MATERIAL_O_CONTRACT,
  PROOF_MATERIAL_O_LICENSE,
  PROOF_MATERIAL_O_PERMIT,
  PROOF_MATERIAL_O_TAX,
  PROOF_MATERIAL_O_OTHER,
  PROTECTION_MODEL,
  PROTECTION_MODEL_COMPENSATORY,
  PUBLIC_ACC_STATUS,
  REL_FRIEND,
  REL_FRIEND_LIST,
  REL_RELATIVE,
  REL_RELATIVE_LIST,
  REL_OP_FIRST_CONTACTOR,
  REL_OP_LEGAL_PERSON,
  REPAY_MODEL,
  REPAY_STATUS,
  REPAY_TIME_RANGE,
  REPAY_WAY,
  RISK_TYPE,
  RISK_TYPE_GROUP,
  RISK_LEVEL,
  RISK_LEVEL_GROUP,
  RISK_TAKING_TYPE,
  SEARCH_DATE_TYPE,
  SEARCH_DATE_TYPE_APPLY,
  SEARCH_DATE_TYPE_LOAN,
  SERVICE_TYPE,
  SERVICE_TYPE_ASSET,
  SERVICE_TYPE_FUND,
  SHAREHOLDER_TYPE,
  STATE_TYPE,
  SUBJECT_PROP,
  SUBJECT_PROP_PERSON,
  SUBJECT_PROP_ORGANIZE,
  TASK_STATUS,
  TASK_STATUS_FAILURE,
  TASK_TYPE,
  TERM_UNIT,
  TERM_UNIT_DAY,
  TERM_UNIT_NATURAL_MONTH,
  WORK_NATURE
}
